spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
#   database Heroku
    platform: postgres
    url: jdbc:postgresql://ec2-3-223-169-166.compute-1.amazonaws.com:5432/da3i75p1cbea5h
    username: tdphhqlrjwmxud
    password: 8bb11ba849a1b9b4eeb04ad935ee4db731fa1bcf965a718fc8a55de559cf1916
    driverClassName: org.postgresql.Driver
